// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuwbasqsjlxfwgloocoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1d2Jhc3Fzamx4ZndnbG9vY29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NTYxODIsImV4cCI6MjA2MDMzMjE4Mn0.jqQapTXa-F-c6eKnUP2_SToMsGYnm8OKb8aVLpJplhE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);