# Generated by Django 3.2.25 on 2025-04-23 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('target_domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domaine cible')),
                ('target_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='IP cible')),
                ('target_type', models.CharField(blank=True, choices=[('website', 'Site Web'), ('webapp', 'Application Web'), ('api', 'API'), ('server', 'Serveur'), ('network', 'Réseau'), ('other', 'Autre')], max_length=20, null=True, verbose_name='Type de cible')),
                ('scope', models.CharField(blank=True, choices=[('internal', 'Interne'), ('external', 'Externe'), ('both', 'Les deux')], max_length=20, null=True, verbose_name='Portée')),
                ('technologies', models.JSONField(blank=True, null=True, verbose_name='Technologies')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='scheduled', max_length=15, verbose_name='Statut')),
                ('target_url', models.URLField(verbose_name='URL cible')),
                ('scan_type', models.CharField(max_length=50, verbose_name='Type de scan')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('findings_summary', models.JSONField(blank=True, null=True, verbose_name='Résumé des résultats')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Scan de sécurité',
                'verbose_name_plural': 'Scans de sécurité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible')], max_length=10, verbose_name='Sévérité')),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('in_progress', 'En cours'), ('resolved', 'Résolue'), ('closed', 'Fermée')], default='open', max_length=15, verbose_name='Statut')),
                ('target_url', models.URLField(blank=True, null=True, verbose_name='URL cible')),
                ('discovered_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de découverte')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notes de résolution')),
                ('cve_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Identifiant CVE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Vulnérabilité',
                'verbose_name_plural': 'Vulnérabilités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Remediation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('remediation_type', models.CharField(max_length=50, verbose_name='Type de remédiation')),
                ('method', models.CharField(max_length=255, verbose_name='Méthode')),
                ('status', models.CharField(choices=[('success', 'Succès'), ('failed', 'Échec'), ('in_progress', 'En cours')], default='in_progress', max_length=15, verbose_name='Statut')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Résultat')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'exécution")),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project', verbose_name='Projet')),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vulnerability', verbose_name='Vulnérabilité')),
            ],
            options={
                'verbose_name': 'Remédiation',
                'verbose_name_plural': 'Remédiations',
                'ordering': ['-executed_at'],
            },
        ),
    ]
